language: java
install :
  - mvn clean install -DskipTests
  - mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:3.0.0-SNAPSHOT:setup-sdk -DbatchAnswers=n
script:
  - mvn clean install -DskipTests
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    tags: true
